language: c
install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev gdisk libblkid-dev e2fslibs-dev
script: |
    ./autogen.sh
    mkdir build
    cd build
    ../configure
    make check
